### ISSUE TITLE
The VIM binding doesn't work

### ISSUE THREAD

**Issue by lmartins** [t9md/atom-lazy-motion#1]
Im using your suggested configuration:

```
# LAZY MOTION
'atom-text-editor':
    'ctrl-s':     'lazy-motion:forward'
    'ctrl-cmd-r': 'lazy-motion:backward'

'atom-text-editor.lazy-motion':
    ']': 'lazy-motion:forward'
    '[': 'lazy-motion:backward'

'atom-text-editor.vim-mode.command-mode':
    's': 'lazy-motion:search-forward'

'.platform-darwin atom-text-editor.lazy-motion[mini]':
    ']':      'lazy-motion:forward'
    '[':      'lazy-motion:backward'
    ';':      'core:confirm'
    'ctrl-g': 'core:cancel'
```

And it does get called when I press `s` in vim mode:
![screenshot 2015-07-13 20 41 06](https://cloud.githubusercontent.com/assets/151981/8659005/88633b9c-299f-11e5-84ba-97ef1a222b23.png)

But for some reason the input for inserting the search string doesn't show up. If I trigger that function via the command palette the it runs fine.

**Comment by t9md** [comment]
Sorry, `lazy-motion:search-forward` not exists, its should `lazy-motion:forward`.
I'll fix in README.md soon.

Thanks for reporting this!

**Comment by t9md** [comment]
Fixed and released

**Comment by lmartins** [comment]
Oh, I should have spotted that. 
Thanks.
