### ISSUE TITLE
Configurations no longer appear on Atom 1.4.0

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-lazy-motion#10]
(Tested, same issue as https://github.com/t9md/atom-smalls/issues/2)

Btw, holy crap, this is **exactly** what I've been looking for from Sublime Text, for years! Thanks a lot!

**Comment by t9md** [comment]
Thanks for encouraging comment!

I stopped middle of improvement for this package from my interest moved to vim-mode-plus.
But I had several idea to solve #6 and actually implemented but stopped.

I will restart this improvement process again in short time..
