### ISSUE TITLE
unpublish from atom package repo, update readme to link to new maintainer

### ISSUE THREAD

**Issue by t9md** [t9md/atom-lazy-motion#16]
- [x]  Update readme to this repo to link to new maintainer's page
- [x] Unpublish from atom.io so that new maitainer can release it with same name.

**Comment by t9md** [comment]
@jrajav
I can unpublish whenever. Do you have any preference for timing?
Maybe some user still using lazy-motion.
But I thinks unpubublishing it is OK since I notified already.

**Comment by jonvuri** [comment]
@t9md I just pushed a commit to prepare for it, https://github.com/jrajav/atom-lazy-motion/commit/8e5dee975259600e72fff7717544deaa93c5e1bb

Look good to you? If so I am ready anytime. Also, are you going to keep this repository around? If not I will want to save the issues before you delete it.

**Comment by t9md** [comment]
Comment out this line.
https://github.com/jrajav/atom-lazy-motion/blob/master/lib/main.coffee#L27

This is one-time warning to notify deprecation of package.

Basically I can't check the change you made or will make, why I will deprecate is, I want my time so not wanting to spend my time for the package I don't use.

I will unpublish lazy-motion from now.
Thank you for taking ownership, I'm appreciate your suggestion.

**Comment by t9md** [comment]
For this repo,  I wont remove, will keep, so don't need to hurry to save past issue.

**Comment by t9md** [comment]
Unpublished DONE.

**Comment by jonvuri** [comment]
I made that fix (entirely removed the deprecation function and its call), thanks for pointing that out.

Also, published, should be up now at https://atom.io/packages/lazy-motion. All done!
