### ISSUE TITLE
repeat last lazy motion to the next match

### ISSUE THREAD

**Issue by jacekkopecky** [t9md/atom-lazy-motion#4]
It would be useful sometimes to have a quick way of repeating the last lazy motion.
Great package, btw, thanks!

**Comment by t9md** [comment]
I can add history feature to pop previously inputed word into lazy-motion's input area.
Is this you are saying? or repeating last-search(confirmed word) with vim-mode's repeat search(integrating vim-mode).

Both features are implemented my [atom-isearch](https://github.com/t9md/atom-isearch) package.

I'm OK to add same feature to lazy-motion.
But want to understand your opinion.
Thanks.

**Comment by t9md** [comment]
I released history features.
For usage, see [my keymap](https://github.com/t9md/atom-lazy-motion#my-setting).

**Comment by jacekkopecky** [comment]
Thank you! I'll have to check out atom-isearch and incremental-search; but this is great.
Would it make sense for `forward-again` to show the next match if the cursor is already on a match?

**Comment by t9md** [comment]
Yes make sense, I noticed this behavior.

Currently it move **next** entry of match.
To keep cursor position if its already on match, it need some code modification.
Is current behavior counter intuitive for you?

PS. Since lazy-motion derived from my experiment on atom-isearch and my motivation moved from isearch to lazy-motion, isearch is not well written than lazy-motion.

Currently code is very duplicated between these two package, I'm considering to merge these to one package to easily switching between isearch and lazy search.

But search word is different, I'm not sure what approach is best.
Any idea?

**Comment by jacekkopecky** [comment]
What I mean is that when I invoke `forward`, land on a match, then immediately invoke `forward-again`, the following match should be offered (no movement of cursor yet, you got that perfectly), so that `confirm` would land on the following match.

Currently, `forward`, `confirm` puts the cursor on a match, and `forward-again`, `confirm` doesn't move the cursor because it's already on a match.

**Comment by jacekkopecky** [comment]
About `atom-isearch` vs `lazy-motion` - I could easily see the two functionalities to be part of one package. I like your philosophy of small keymap footprint (or no keymap at all by default), so they might be different commands for the user to put on the keys they like.

Alternatively, I've noticed that the `incremental-search` package (not `atom-isearch`) has flags for regex/literal and case-sensitive/ignore-case, in a similar vein I could see it having a fuzzy option. This might be another way of handling the lazy-search v. isearch choice in a single package.

**Comment by t9md** [comment]
> Currently, forward, confirm puts the cursor on a match, and forward-again, confirm doesn't move the cursor because it's already on a match.

OK, and your suggestion is move next match in this case right?

**Comment by jacekkopecky** [comment]
Exactly, yes. 8-)

**Comment by t9md** [comment]
Thanks, I understand now. I'll do experiment for that first.

P.S. sorry I still have some difficulty to understand english. So sometime need confirmation about my understanding.

**Comment by jacekkopecky** [comment]
Don't worry @t9md - if you ask me, more people on the internet should seek clarification and confirmation of their understanding. 8-)

**Comment by t9md** [comment]
After I think about your suggestion and check behavior.
I understood your suggestion was right.

So I changed default behavior to behave as you've suggested.
Thanks. Nice catch!

**Comment by jacekkopecky** [comment]
Super, thank you!
