### ISSUE TITLE
Preserve the search string?

### ISSUE THREAD

**Issue by bronson** [t9md/atom-lazy-motion#7]
Find remembers the search string.  If I hit `cmd-f`, type something, hit `esc`, and then hit `cmd-f` again, the string is still in the text box.

Lazy Motion doesn't seem to remember the search string.  I hit `ctrl-s`, type something, hit `esc`, and hit `ctrl-s` again, the search box is empty.

I think it would be nice if Lazy Motion remembered the search string like Find.

**Comment by bronson** [comment]
(and, hope things are going well.  Trying to devote some more time to Atom.  I'm blown away by the vim-mode work you've done.)

**Comment by t9md** [comment]
Aside from issue(ill check later).
Did tou tried vim-mode-plus?
Im mainly use inclemental search on vim-mode-plus rather than this package recentlly.
Off course ill maintain this pack.

**Comment by bronson** [comment]
I haven't but this will inspire me to try it sooner

**Comment by t9md** [comment]
When I released vim-mode-plus what was in my mind is how you  say about this!? Im very looking forward feedback from you!
